const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaults={interventions:[],fumure:[],products:[],settings:{}}; let db={...defaults};
const idb=window.indexedDB?indexedDB.open('terres-troupeau',1):null;
function save(){localStorage.setItem('tt-db',JSON.stringify(db)); if(idb){idb.onupgradeneeded=e=>e.target.result.createObjectStore('state');idb.onsuccess=e=>{let t=e.target.result.transaction('state','readwrite');t.objectStore('state').put(db,'db')}} render()}
function load(){try{let x=JSON.parse(localStorage.getItem('tt-db'));if(x)db={...defaults,...x}}catch{} if(!db.parcelles){db.parcelles=SEED.parcelles;db.history=SEED.history;db.codes=SEED.codes;db.cultures=SEED.cultures;save()} render()}
function dl(name,text,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click()}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function nav(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id===view));$$('nav button').forEach(x=>x.classList.toggle('selected',x.dataset.go===view));scrollTo(0,0)}
$$('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));
function render(){let camps=[...new Set(db.history.flatMap(x=>Object.keys(x.campagnes||{})))].sort();let camp=$('#campaign');camp.innerHTML=camps.map(x=>`<option>${x}</option>`).join('');$('#filterCamp').innerHTML='<option value="">Toutes campagnes</option>'+camps.map(x=>`<option>${x}</option>`).join('');let year=camp.value||'2026';let area=db.parcelles.reduce((a,p)=>a+Number(p.surface||0),0);$('#stats').innerHTML=`<div class="stat"><b>${db.parcelles.length}</b><span>parcelles PAC</span></div><div class="stat"><b>${area.toFixed(2)}</b><span>ha admissibles</span></div><div class="stat"><b>${db.interventions.length}</b><span>interventions</span></div>`;let recent=db.interventions.slice(-4).reverse();$('#recent').innerHTML=recent.length?recent.map(interCard).join(''):'<p class="muted">Aucune intervention saisie. Commencez par le bouton jaune.</p>';$('#interList').innerHTML=filterInterventions().map(interCard).join('')||'<p class="muted">Aucune intervention pour ce filtre.</p>';$('#parcelList').innerHTML=db.parcelles.slice(0,100).map(p=>`<div class="card"><div><strong>${esc(p.id)}</strong><span class="tag">îlot ${esc(p.ilot)} · parcelle ${esc(p.parcelle)}</span><div class="muted">Culture 2026 : ${esc(p.culture)} · ${esc(p.commune)}</div></div><div class="amount"><b>${Number(p.surface).toFixed(2)}</b><br><small>ha</small></div></div>`).join('');let total=db.fumure.reduce((a,x)=>a+Number(x.nTotal||0),0);$('#fumureSummary').innerHTML=`<span class="eyebrow">AZOTE APPORTÉ</span><br><strong>${total.toFixed(1)} kg N</strong><br><span class="muted">Calculé à partir des teneurs renseignées dans le catalogue. À valider selon analyses, effluents et réglementation.</span>`;$('#fumureList').innerHTML=db.fumure.map(f=>`<div class="card"><div><strong>${esc(f.parcelle)}</strong><div class="muted">${esc(f.produit)} · ${esc(f.dose)} t/ha · ${esc(f.statut||'prévu')}</div></div><div class="amount">${Number(f.nTotal||0).toFixed(1)} kg N</div></div>`).join('')||'<p class="muted">Aucun apport enregistré.</p>';$('#culturesEdit').value=(db.cultures||[]).join(', ');$('#productsEdit').value=(db.products||[]).map(p=>`${p.name};${p.n||''};${p.p||''};${p.k||''}`).join('\n')}
function filterInterventions(){let q=($('#filterInter').value||'').toLowerCase(),c=$('#filterCamp').value;return db.interventions.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!c||x.campagne===c))}
function interCard(x){return `<div class="card"><div><strong>${esc(x.type||'Intervention')}</strong><span class="tag">${esc(x.date||'sans date')}</span><div class="muted">${esc(x.parcelle)} · ${esc(x.produit||x.materiel||'—')}</div></div><div class="amount">${esc(x.dose||'')} ${esc(x.unite||'')}</div></div>`}
function modal(kind){let isF=kind==='fumure', opts=db.parcelles.map(p=>`<option>${esc(p.id)}</option>`).join('');$('#modalContent').innerHTML=`<p class="eyebrow">NOUVELLE SAISIE</p><h2>${isF?'Ajouter un apport':'Ajouter une intervention'}</h2><div class="formgrid"><label>Parcelle<select id="fParcelle">${opts}</select></label><label>Date<input id="fDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label>${isF?`<label>Produit / effluent<input id="fProduit" placeholder="À renseigner / valider"></label><label>Dose (t/ha)<input id="fDose" type="number" step="0.01"></label><label>Surface apport (ha)<input id="fSurface" type="number" step="0.01"></label><label>Statut<select id="fStatut"><option>prévu</option><option>réalisé</option></select></label><label class="full">Notes<textarea id="fNotes"></textarea></label>`:`<label>Type<select id="fType"><option>Semis</option><option>Travail du sol</option><option>Fertilisation</option><option>Traitement bio / phyto</option><option>Récolte</option><option>Irrigation</option><option>Épandage effluents</option><option>Autre</option></select></label><label>Produit / matériel<input id="fProduit"></label><label>Dose<input id="fDose"></label><label>Unité<input id="fUnite" placeholder="kg/ha, L/ha…"></label><label>Temps (h)<input id="fTemps" type="number" step="0.1"></label><label class="full">Notes<textarea id="fNotes"></textarea></label>`}</div><div class="form-actions"><button id="cancel">Annuler</button><button id="submit" class="primary">Enregistrer</button></div>`;$('#modal').hidden=false;$('#cancel').onclick=()=>$('#modal').hidden=true;$('#submit').onclick=()=>{let p=$('#fParcelle').value,x={parcelle:p,date:$('#fDate').value,produit:$('#fProduit').value,dose:$('#fDose').value,notes:$('#fNotes').value};if(isF){x.surface=$('#fSurface').value;x.statut=$('#fStatut').value;let prod=db.products.find(z=>z.name===x.produit);x.nTotal=prod?Number(x.dose||0)*Number(x.surface||0)*Number(prod.n||0):0;db.fumure.push(x)}else{x.type=$('#fType').value;x.unite=$('#fUnite').value;x.temps=$('#fTemps').value;x.campagne=$('#campaign').value;db.interventions.push(x)}$('#modal').hidden=true;save()}}
$('#newInter').onclick=()=>modal('inter');$('#newFumure').onclick=()=>modal('fumure');$('#closeModal').onclick=()=>$('#modal').hidden=true;$('#filterInter').oninput=render;$('#filterCamp').onchange=render;$('#campaign').onchange=render;
$('#saveSettings').onclick=()=>{db.cultures=$('#culturesEdit').value.split(',').map(x=>x.trim()).filter(Boolean);db.products=$('#productsEdit').value.split('\n').map(x=>{let a=x.split(';');return{name:(a[0]||'').trim(),n:Number(a[1]||0),p:Number(a[2]||0),k:Number(a[3]||0)}}).filter(x=>x.name);save();alert('Référentiels enregistrés.')};
$('#exportJson').onclick=()=>dl('terres-troupeau-sauvegarde.json',JSON.stringify(db,null,2),'application/json');
function rows(){return [['type','date','campagne','parcelle','culture','produit','dose','unite','surface','statut','N_total','notes'],...db.interventions.map(x=>['intervention',x.date,x.campagne,x.parcelle,'',x.produit,x.dose,x.unite,'','', '',x.notes]),...db.fumure.map(x=>['fumure',x.date||'',x.campagne||'',x.parcelle,'',x.produit,x.dose,'t/ha',x.surface,x.statut,x.nTotal,x.notes])]}function csv(){return rows().map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(';')).join('\n')};$('#exportCsv').onclick=()=>dl('terres-troupeau.csv','\ufeff'+csv(),'text/csv');$('#exportXls').onclick=()=>dl('terres-troupeau.xls','<table>'+rows().map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</table>','application/vnd.ms-excel');$('#importJson').onchange=e=>{let f=e.target.files[0],r=new FileReader();r.onload=()=>{try{db={...defaults,...JSON.parse(r.result)};save();alert('Sauvegarde importée.')}catch{alert('Fichier JSON invalide.')}};r.readAsText(f)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');load();
